local M = {}

function M.get(c, _)
  return {
    ["@lsp.type.boolean"] = "@boolean",
    ["@lsp.type.builtinType"] = "@type.builtin",
    ["@lsp.type.class"] = "@type",
    ["@lsp.type.comment"] = "@comment",
    ["@lsp.type.decorator"] = "@attribute",
    ["@lsp.type.deriveHelper"] = "@attribute",
    ["@lsp.type.enum"] = "@type",
    ["@lsp.type.enumMember"] = "@constant",
    ["@lsp.type.escapeSequence"] = "@string.escape",
    ["@lsp.type.event"] = "@label",
    ["@lsp.type.formatSpecifier"] = "@character.printf",
    ["@lsp.type.function"] = "@function",
    ["@lsp.type.generic"] = "@type",
    ["@lsp.type.interface"] = "@type",
    ["@lsp.type.keyword"] = "@keyword",
    ["@lsp.type.lifetime"] = "@keyword.storage",
    ["@lsp.type.macro"] = "@function.macro",
    ["@lsp.type.method"] = "@function.method",
    ["@lsp.type.modifier"] = "@keyword.storage",
    ["@lsp.type.namespace"] = "@module",
    ["@lsp.type.namespace.python"] = "@variable",
    ["@lsp.type.number"] = "@number",
    ["@lsp.type.operator"] = "@operator",
    ["@lsp.type.parameter"] = "@variable.parameter",
    ["@lsp.type.parameter.lua"] = "@variable.parameter.lua",
    ["@lsp.type.property"] = "@property",
    ["@lsp.type.regexp"] = "@string.regexp",
    ["@lsp.type.selfKeyword"] = "@variable.builtin",
    ["@lsp.type.selfTypeKeyword"] = "@variable.builtin",
    ["@lsp.type.string"] = "@string",
    ["@lsp.type.struct"] = "@type",
    ["@lsp.type.type"] = "@type",
    ["@lsp.type.typeAlias"] = "@type.definition",
    ["@lsp.type.typeParameter"] = "@type",
    ["@lsp.type.variable"] = {},
    ["@lsp.type.unresolvedReference"] = { fg = c.phosphor_bright, undercurl = true, sp = c.phosphor_bright },

    ["@lsp.typemod.class.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.enum.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.enumMember.defaultLibrary"] = "@constant.builtin",
    ["@lsp.typemod.function.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.function.defaultLibrary.lua"] = "@function.builtin",
    ["@lsp.typemod.interface.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.macro.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.method.defaultLibrary"] = "@function.builtin",
    ["@lsp.typemod.struct.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.type.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.typeParameter.defaultLibrary"] = "@type.builtin",
    ["@lsp.typemod.variable.defaultLibrary"] = "@variable.builtin",
    ["@lsp.typemod.keyword.async"] = "@keyword.coroutine",
    ["@lsp.typemod.keyword.injected"] = "@keyword",
    ["@lsp.typemod.operator.injected"] = "@operator",
    ["@lsp.typemod.string.injected"] = "@string",
    ["@lsp.typemod.variable.injected"] = "@variable",
    ["@lsp.typemod.variable.callable"] = "@function",
    ["@lsp.typemod.variable.static"] = "@constant",
    ["@lsp.typemod.parameter.declaration"] = "@variable.parameter",
    ["@lsp.typemod.parameter.declaration.lua"] = "@variable.parameter.lua",
    ["@lsp.typemod.parameter.definition"] = "@variable.parameter",
    ["@lsp.typemod.parameter.readonly"] = "@constant",
    ["@lsp.typemod.variable.declaration"] = "@variable",
    ["@lsp.typemod.variable.definition"] = "@variable",
    ["@lsp.typemod.variable.readonly"] = "@constant",
  }
end

return M
