local M = {}

function M.get(c, _)
  return {
    ["@annotation"] = "PreProc",
    ["@attribute"] = "PreProc",
    ["@attribute.builtin"] = "Special",
    ["@boolean"] = "Boolean",
    ["@boolean.lua"] = "@boolean",
    ["@character"] = "Character",
    ["@character.printf"] = "SpecialChar",
    ["@character.special"] = "SpecialChar",
    ["@comment"] = "Comment",
    ["@comment.documentation"] = { fg = c.phosphor_dim, italic = true },
    ["@comment.error"] = "DiagnosticError",
    ["@comment.warning"] = "DiagnosticWarn",
    ["@comment.todo"] = "Todo",
    ["@comment.note"] = "DiagnosticHint",
    ["@comment.info"] = "DiagnosticInfo",
    ["@comment.hint"] = "DiagnosticHint",
    ["@comment.gitcommit"] = "gitcommitComment",
    ["@constant"] = "Constant",
    ["@constant.lua"] = "@constant",
    ["@constant.builtin"] = "Special",
    ["@constant.macro"] = "Define",
    ["@variable"] = "Identifier",
    ["@variable.builtin"] = { fg = c.phosphor_bright, italic = true },
    ["@variable.parameter"] = { fg = c.phosphor_soft },
    ["@variable.parameter.builtin"] = { fg = c.phosphor_dim, italic = true },
    ["@variable.parameter.lua"] = "@variable.parameter",
    ["@module"] = "Directory",
    ["@module.builtin"] = { fg = c.phosphor_bright, italic = true },
    ["@namespace"] = "@module",
    ["@namespace.builtin"] = "@variable.builtin",
    ["@parameter"] = "@variable.parameter",
    ["@preproc"] = "PreProc",
    ["@none"] = {},
    ["@label"] = "Label",
    ["@string"] = "String",
    ["@string.documentation"] = { fg = c.phosphor_soft, italic = true },
    ["@string.regexp"] = { fg = c.phosphor_bright },
    ["@string.escape"] = "SpecialChar",
    ["@string.special"] = "Special",
    ["@string.special.symbol"] = "@markup.link.label",
    ["@string.special.url"] = "@markup.link.url",
    ["@string.gitcommit"] = "String",
    ["@number"] = "Number",
    ["@number.float"] = "Float",
    ["@type"] = "Type",
    ["@type.ruby"] = "@type",
    ["@type.builtin"] = { fg = c.phosphor_bright, bold = true },
    ["@type.definition"] = "Typedef",
    ["@type.qualifier"] = "StorageClass",
    ["@property"] = { fg = c.phosphor },
    ["@function"] = "Function",
    ["@function.builtin"] = { fg = c.phosphor_bright, bold = true },
    ["@function.call"] = "Function",
    ["@function.macro"] = "Macro",
    ["@function.method"] = "Function",
    ["@function.method.call"] = "Function",
    ["@constructor"] = { fg = c.phosphor_bright },
    ["@operator"] = "Operator",
    ["@keyword"] = "Keyword",
    ["@keyword.conditional"] = "Conditional",
    ["@keyword.coroutine"] = "Keyword",
    ["@keyword.debug"] = "Debug",
    ["@keyword.directive"] = "PreProc",
    ["@keyword.directive.define"] = "Define",
    ["@keyword.exception"] = "Exception",
    ["@keyword.function"] = "Keyword",
    ["@keyword.import"] = "Include",
    ["@keyword.operator"] = "Operator",
    ["@keyword.operator.lua"] = "Statement",
    ["@keyword.gitcommit"] = "Keyword",
    ["@keyword.repeat"] = "Repeat",
    ["@keyword.return"] = "Keyword",
    ["@keyword.storage"] = "StorageClass",
    ["@punctuation.bracket"] = { fg = c.phosphor_faint },
    ["@punctuation.delimiter"] = "Delimiter",
    ["@punctuation.special"] = "Special",
    ["@punctuation.special.markdown"] = "@punctuation.special",
    ["@tag"] = "Tag",
    ["@tag.attribute"] = "Special",
    ["@tag.builtin"] = "Tag",
    ["@tag.delimiter"] = "Delimiter",
    ["@diff.plus"] = "Added",
    ["@diff.minus"] = "Removed",
    ["@diff.delta"] = "Changed",
    ["@markup"] = "@none",
    ["@markup.emphasis"] = { italic = true },
    ["@markup.environment"] = "Macro",
    ["@markup.environment.name"] = "Type",
    ["@markup.heading"] = { fg = c.phosphor_bright, bold = true },
    ["@markup.heading.1"] = { fg = c.phosphor_bright, bold = true },
    ["@markup.heading.2"] = { fg = c.phosphor, bold = true },
    ["@markup.heading.3"] = { fg = c.phosphor_soft, bold = true },
    ["@markup.heading.4"] = { fg = c.phosphor_soft },
    ["@markup.heading.5"] = { fg = c.phosphor_dim, bold = true },
    ["@markup.heading.6"] = { fg = c.phosphor_dim },
    ["@markup.heading.1.markdown"] = "@markup.heading.1",
    ["@markup.heading.2.markdown"] = "@markup.heading.2",
    ["@markup.heading.3.markdown"] = "@markup.heading.3",
    ["@markup.heading.4.markdown"] = "@markup.heading.4",
    ["@markup.heading.5.markdown"] = "@markup.heading.5",
    ["@markup.heading.6.markdown"] = "@markup.heading.6",
    ["@markup.heading.gitcommit"] = "gitcommitSummary",
    ["@markup.italic"] = { italic = true },
    ["@markup.link"] = { fg = c.phosphor_soft, underline = true },
    ["@markup.link.label"] = "SpecialChar",
    ["@markup.link.label.symbol"] = "@markup.link.label",
    ["@markup.link.url"] = "Underlined",
    ["@markup.list"] = { fg = c.phosphor_faint },
    ["@markup.list.markdown"] = { fg = c.phosphor_soft, bold = true },
    ["@markup.list.checked"] = { fg = c.phosphor_soft, bold = true },
    ["@markup.list.unchecked"] = { fg = c.phosphor_dim },
    ["@markup.math"] = "Special",
    ["@markup.raw"] = "String",
    ["@markup.raw.block"] = { fg = c.phosphor_soft, bg = c.glow_low },
    ["@markup.raw.markdown_inline"] = { fg = c.phosphor_bright, bg = c.glow_medium },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.strong"] = { bold = true },
    ["@markup.underline"] = { underline = true },
  }
end

return M
